services:
  api:
    build:
      context: ./restapi-demo
    container_name: demo_api_node
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_started
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=kelompok8
      - DB_NAME=demo_api
      - JWT_SECRET=kelompok8terbaik
      - PORT=5000
